1711dz
fd1-53-17/ZuenokHanna pull request #11
Opened 2017-11-17 19:15 UTC by ZuenokHanna

@antonkulakov-it  please review

2017-11-19 20:48 UTC, antonkulakov-it requested changes

2017-11-19 20:48 UTC, antonkulakov-it commented on 1711dz/1/CSS/cards2.css
> +    background-image: url(cards2.png);
а где же сам файл?

2017-11-21 16:50 UTC, ZuenokHanna commented
@antonkulakov-it  please review

2017-11-22 04:11 UTC, antonkulakov-it approved these changes

2017-11-22 04:14 UTC, merged