0111dz
fd1-53-17/ZuenokHanna pull request #3
Opened 2017-11-02 09:55 UTC by ZuenokHanna

@antonkulakov-it  please review

2017-11-03 04:13 UTC, antonkulakov-it requested changes

2017-11-03 04:13 UTC, antonkulakov-it commented on DIARY.html
> +<! DOCTYPE HTML>
между восклицательным знаком и словом doctype не должно быть пробелов.

2017-11-03 04:13 UTC, antonkulakov-it commented on DIARY.html
> +        <p>&copy бородатый <a href="https://preview.c9users.io/hanna26/hanna26/DIARY.html" target="_blank" title="подсказка2">анекдот</a></p>
мнемоника должна заканчиваться точкой с запятой.

2017-11-03 04:13 UTC, antonkulakov-it commented on VIZBOR/vechno_student.html
> +<! DOCTYPE HTML>
между восклицательным знаком и словом doctype не должно быть пробелов.

2017-11-03 04:13 UTC, antonkulakov-it commented on VIZBOR/vechno_student.html
> +обретает человек профессию, и песни  студентов  -  как  записки
не заменен минус на мнемонику

2017-11-03 04:13 UTC, antonkulakov-it commented on VIZBOR/vechno_student.html
> +которую студенчество по праву считает  "своей",  хотя  написана
кавычки не заменены на мнемонику

2017-11-03 04:13 UTC, antonkulakov-it commented on VIZBOR/vizbor.html
> +<! DOCTYPE HTML>
между восклицательным знаком и словом doctype не должно быть пробелов.

2017-11-07 17:06 UTC, ZuenokHanna commented
@antonkulakov-it  please review

2017-11-07 17:27 UTC, ZuenokHanna commented
@antonkulakov-it  please review

2017-11-08 03:53 UTC, antonkulakov-it approved these changes

2017-11-08 03:53 UTC, merged